### ISSUE TITLE
请问有pytorch 转onnx的例子吗

### ISSUE THREAD

**Issue by scuizhibin** [lesliejackson/TensorRT7-DCNv2-Plugin#1]

**Comment by lesliejackson** [comment]
可以看看官方文档 https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html

**Comment by scuizhibin** [comment]
作者你好，我想问一下，配套的pytorch op 算子是哪一个，有链接推荐吗？我使用网上最新的DCN算子导入到pytorch中，解析pth文件时候出现function importDCNv2:[8] Assertion failed: inputs.at(2).is_tensor()。

**Comment by lesliejackson** [comment]
DCNv2的实现参考https://github.com/CaoWGG/TensorRT-CenterNet这个库

**Comment by scuizhibin** [comment]
不好意思，有对应的安装pytorch&nbsp;op算子的代码吗？我安装的版本不对，导致解析的时候出了问题。


---原始邮件---
发件人: &quot;Yun Yang&quot;<notifications@github.com&gt;
发送时间: 2021年3月4日(周四) 晚上7:20
收件人: &quot;lesliejackson/TensorRT7-DCNv2-Plugin&quot;<TensorRT7-DCNv2-Plugin@noreply.github.com&gt;;
抄送: &quot;scuizhibin&quot;<1017948396@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题: Re: [lesliejackson/TensorRT7-DCNv2-Plugin] 请问有pytorch 转onnx的例子吗 (#1)




 
DCNv2的实现参考 https://github.com/CaoWGG/TensorRT-CenterNet 这个库
 
&mdash;

**Comment by lesliejackson** [comment]
https://github.com/CaoWGG/TensorRT-CenterNet/blob/f949252e37b51e60f873808f46d3683f15735e79/readme/dcn/modules/deform_conv.py

这个是pytorch的算子

**Comment by scuizhibin** [comment]
谢谢了，大佬。配合你写的插件和指南，我想应该没问题了


---原始邮件---
发件人: &quot;Yun Yang&quot;<notifications@github.com&gt;
发送时间: 2021年3月4日(周四) 晚上7:56
收件人: &quot;lesliejackson/TensorRT7-DCNv2-Plugin&quot;<TensorRT7-DCNv2-Plugin@noreply.github.com&gt;;
抄送: &quot;scuizhibin&quot;<1017948396@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题: Re: [lesliejackson/TensorRT7-DCNv2-Plugin] 请问有pytorch 转onnx的例子吗 (#1)




 
https://github.com/CaoWGG/TensorRT-CenterNet/blob/f949252e37b51e60f873808f46d3683f15735e79/readme/dcn/modules/deform_conv.py
 
这个是pytorch的算子
 
&mdash;

**Comment by lesliejackson** [comment]
ok，有问题再开issue，这个我先关了就
